#version 450

layout(local_size_x = 256) in;

layout(binding = 0, std430) suppress readonly buffer InA {
    float a[];
};

layout(binding = 1, std430) suppress readonly buffer InB {
    float b[];
};

layout(binding = 2, std430) suppress writeonly buffer OutC {
    float c[];
};

layout(push_constant) uniform Push {
    uint n;
};

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= n) return;
    c[i] = a[i] + b[i];
}
